-- Seed data for communities table

INSERT INTO communities (id, name, short_description, description, cover_image, created_at, created_by, is_private, deleted_at) VALUES
(1, 'Golang Việt Nam', 'Cộng đồng lập trình viên Golang tại Việt Nam', 'Nơi chia sẻ kiến thức, kinh nghiệm và thảo luận về ngôn ngữ lập trình Golang. Chúng tôi là một cộng đồng năng động, luôn sẵn sàng giúp đỡ những người mới bắt đầu và chia sẻ các best practices.', 'https://picsum.photos/seed/golang/800/400', NOW() - INTERVAL '80 days', 5, false, NULL),
(2, 'React Developers', 'Cộng đồng React và Frontend Development', 'Tập hợp các lập trình viên Frontend, đặc biệt là những người làm việc với React, Next.js, và các công nghệ liên quan. Chia sẻ tips, tricks và các dự án thú vị.', 'https://picsum.photos/seed/react/800/400', NOW() - INTERVAL '75 days', 4, false, NULL),
(3, 'DevOps Vietnam', 'Cộng đồng DevOps, CI/CD và Cloud', 'Nơi thảo luận về DevOps practices, Kubernetes, Docker, CI/CD pipelines, và cloud infrastructure. Chúng tôi chia sẻ kinh nghiệm triển khai và vận hành hệ thống.', 'https://picsum.photos/seed/devops/800/400', NOW() - INTERVAL '70 days', 3, false, NULL),
(4, 'Python Community', 'Cộng đồng lập trình Python', 'Từ web development với Django/Flask đến Data Science và Machine Learning. Python cho mọi người và mọi mục đích.', 'https://picsum.photos/seed/python/800/400', NOW() - INTERVAL '65 days', 7, false, NULL),
(5, 'Mobile Dev Hub', 'Flutter, React Native và Mobile Development', 'Cộng đồng phát triển ứng dụng di động với Flutter, React Native, và native development. Chia sẻ UI/UX, performance optimization và app architecture.', 'https://picsum.photos/seed/mobile/800/400', NOW() - INTERVAL '60 days', 8, false, NULL),
(6, 'Cybersecurity VN', 'An ninh mạng và Bảo mật', 'Thảo luận về security best practices, penetration testing, và cách bảo vệ ứng dụng khỏi các lỗ hổng bảo mật. Chia sẻ các case study và incident response.', 'https://picsum.photos/seed/security/800/400', NOW() - INTERVAL '55 days', 9, false, NULL),
(7, 'Data Science Vietnam', 'Data Analytics, ML và AI', 'Cộng đồng Data Science, Machine Learning và Artificial Intelligence. Thảo luận về algorithms, models, và real-world applications.', 'https://picsum.photos/seed/datascience/800/400', NOW() - INTERVAL '50 days', 15, false, NULL),
(8, 'Web3 & Blockchain', 'Công nghệ Blockchain và Web3', 'Khám phá thế giới của blockchain, smart contracts, DeFi và NFTs. Chia sẻ về Ethereum, Solana và các platform khác.', 'https://picsum.photos/seed/web3/800/400', NOW() - INTERVAL '45 days', 11, false, NULL),
(9, 'UI/UX Designers', 'Thiết kế giao diện và trải nghiệm người dùng', 'Cộng đồng designer và developer quan tâm đến UI/UX. Chia sẻ design systems, prototypes và user research insights.', 'https://picsum.photos/seed/uiux/800/400', NOW() - INTERVAL '40 days', 14, false, NULL),
(10, 'Backend Engineering', 'Kiến trúc hệ thống Backend', 'Thảo luận về system design, microservices, databases, caching, và scalability. Từ monolith đến distributed systems.', 'https://picsum.photos/seed/backend/800/400', NOW() - INTERVAL '35 days', 1, false, NULL),
(11, 'QA & Testing', 'Quality Assurance và Automation Testing', 'Cộng đồng QA Engineers. Chia sẻ về test automation, test strategies, và quality metrics. Từ unit testing đến E2E testing.', 'https://picsum.photos/seed/qa/800/400', NOW() - INTERVAL '30 days', 10, false, NULL),
(12, 'Cloud Architecture', 'AWS, Azure và GCP', 'Thảo luận về cloud architecture, serverless, và cloud-native applications. Best practices cho multi-cloud và hybrid cloud.', 'https://picsum.photos/seed/cloud/800/400', NOW() - INTERVAL '25 days', 13, false, NULL),
(13, 'Tech Career', 'Nghề nghiệp và Phát triển sự nghiệp IT', 'Chia sẻ về career path, interview experiences, salary negotiation, và work-life balance trong ngành IT.', 'https://picsum.photos/seed/career/800/400', NOW() - INTERVAL '20 days', 11, false, NULL),
(14, 'Startup Tech', 'Công nghệ cho Startup', 'Thảo luận về tech stack cho startups, MVP development, scaling, và technical decisions cho early-stage companies.', 'https://picsum.photos/seed/startup/800/400', NOW() - INTERVAL '15 days', 5, false, NULL),
(15, 'Code Review Club', 'Code Review và Best Practices', 'Nơi chia sẻ code để nhận feedback, học hỏi coding standards, design patterns, và clean code principles.', 'https://picsum.photos/seed/codereview/800/400', NOW() - INTERVAL '10 days', 2, false, NULL);

-- Reset sequence
SELECT setval('communities_id_seq', 15, true);
